name: Test Suite
on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      
      - name: Run tests
        run: |
          nix build --reference-lock-file flake.lock --option allow-import-from-derivation false --print-build-logs ./tests#integration-test-standalone-standard-basics
